name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please check the [roadmap](https://github.com/ggagosh/openmango/blob/main/docs/features.md) to see if this is already planned.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear description of the feature you'd like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the problem this would solve or the workflow it would improve
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Query & Performance
        - Document Browser
        - Aggregation Builder
        - Schema Explorer
        - Transfer (Import/Export)
        - Connection Manager
        - Forge Shell
        - Themes & UI
        - Keyboard Shortcuts
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've considered
    validations:
      required: false
