# Build optimizations for macOS
# Requires: brew install lld

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/lld/bin/ld64.lld"]
runner = "./scripts/cargo_runner_macos.sh"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/lld/bin/ld64.lld"]
runner = "./scripts/cargo_runner_macos.sh"
