use gpui::{App, KeyBinding, actions};

actions!(
    openmango,
    [
        QuitApp,
        NewConnection,
        OpenSelection,
        OpenSelectionPreview,
        EditConnection,
        DisconnectConnection,
        CopySelectionName,
        CopyConnectionUri,
        RenameCollection,
        DeleteSelection,
        TransferExport,
        TransferImport,
        TransferCopy,
        CreateDatabase,
        CreateCollection,
        CreateIndex,
        InsertDocument,
        RefreshView,
        CloseTab,
        NextTab,
        PrevTab,
        FindInResults,
        CloseSearch,
        SaveDocument,
        DiscardDocumentChanges,
        EditDocumentJson,
        CopyDocumentJson,
        DuplicateDocument,
        DeleteDocument,
        DeleteCollection,
        DeleteDatabase,
        DeleteConnection,
        PasteDocuments,
        EditValueType,
        RenameField,
        RemoveSelectedField,
        AddField,
        AddElement,
        RemoveMatchingValues,
        CopyValue,
        CopyKey,
        ShowDocumentsSubview,
        ShowIndexesSubview,
        ShowStatsSubview,
        ShowAggregationSubview,
        RunAggregation,
        FormatAggregationStage,
        ClearAggregationStage,
        SelectPrevAggregationStage,
        SelectNextAggregationStage,
        MoveAggregationStageUp,
        MoveAggregationStageDown,
        DuplicateAggregationStage,
        DeleteAggregationStage,
        ToggleAggregationStageEnabled,
        FindInSidebar,
        CloseSidebarSearch,
        OpenActionBar,
    ]
);

pub fn bind_default_keymap(cx: &mut App) {
    cx.bind_keys(default_keybindings());
}

fn default_keybindings() -> Vec<KeyBinding> {
    vec![
        KeyBinding::new("enter", OpenSelection, Some("Sidebar")),
        KeyBinding::new("return", OpenSelection, Some("Sidebar")),
        KeyBinding::new("cmd-enter", OpenSelectionPreview, Some("Sidebar")),
        KeyBinding::new("ctrl-enter", OpenSelectionPreview, Some("Sidebar")),
        KeyBinding::new("cmd-e", EditConnection, Some("Sidebar")),
        KeyBinding::new("ctrl-e", EditConnection, Some("Sidebar")),
        KeyBinding::new("cmd-shift-d", DisconnectConnection, Some("Sidebar")),
        KeyBinding::new("ctrl-shift-d", DisconnectConnection, Some("Sidebar")),
        KeyBinding::new("cmd-c", CopySelectionName, Some("Sidebar && !Input")),
        KeyBinding::new("ctrl-c", CopySelectionName, Some("Sidebar && !Input")),
        KeyBinding::new("cmd-shift-c", CopyConnectionUri, Some("Sidebar && !Input")),
        KeyBinding::new("ctrl-shift-c", CopyConnectionUri, Some("Sidebar && !Input")),
        KeyBinding::new("f2", RenameCollection, Some("Sidebar && !Input")),
        KeyBinding::new("backspace", DeleteSelection, Some("Sidebar && !Input")),
        KeyBinding::new("delete", DeleteSelection, Some("Sidebar && !Input")),
        KeyBinding::new("cmd-shift-n", CreateDatabase, Some("Sidebar")),
        KeyBinding::new("ctrl-shift-n", CreateDatabase, Some("Sidebar")),
        KeyBinding::new("cmd-n", CreateCollection, Some("Sidebar")),
        KeyBinding::new("ctrl-n", CreateCollection, Some("Sidebar")),
        KeyBinding::new("cmd-alt-e", TransferExport, Some("Sidebar && !Input")),
        KeyBinding::new("ctrl-alt-e", TransferExport, Some("Sidebar && !Input")),
        KeyBinding::new("cmd-alt-i", TransferImport, Some("Sidebar && !Input")),
        KeyBinding::new("ctrl-alt-i", TransferImport, Some("Sidebar && !Input")),
        KeyBinding::new("cmd-alt-c", TransferCopy, Some("Sidebar && !Input")),
        KeyBinding::new("ctrl-alt-c", TransferCopy, Some("Sidebar && !Input")),
        KeyBinding::new("cmd-n", InsertDocument, Some("Documents && !Indexes && !Stats")),
        KeyBinding::new("ctrl-n", InsertDocument, Some("Documents && !Indexes && !Stats")),
        KeyBinding::new("cmd-n", CreateIndex, Some("Documents && Indexes")),
        KeyBinding::new("ctrl-n", CreateIndex, Some("Documents && Indexes")),
        KeyBinding::new("cmd-n", CreateCollection, Some("Database")),
        KeyBinding::new("ctrl-n", CreateCollection, Some("Database")),
        KeyBinding::new("cmd-n", NewConnection, Some("Workspace && Welcome")),
        KeyBinding::new("ctrl-n", NewConnection, Some("Workspace && Welcome")),
        KeyBinding::new("cmd-n", NewConnection, Some("Workspace && Databases")),
        KeyBinding::new("ctrl-n", NewConnection, Some("Workspace && Databases")),
        KeyBinding::new("cmd-n", NewConnection, Some("Workspace && Collections")),
        KeyBinding::new("ctrl-n", NewConnection, Some("Workspace && Collections")),
        KeyBinding::new("cmd-shift-n", CreateDatabase, Some("Workspace && !Documents")),
        KeyBinding::new("ctrl-shift-n", CreateDatabase, Some("Workspace && !Documents")),
        KeyBinding::new("cmd-w", CloseTab, Some("Workspace")),
        KeyBinding::new("ctrl-w", CloseTab, Some("Workspace")),
        KeyBinding::new("ctrl-tab", NextTab, Some("Workspace")),
        KeyBinding::new("ctrl-shift-tab", PrevTab, Some("Workspace")),
        KeyBinding::new("cmd-r", RefreshView, Some("Workspace")),
        KeyBinding::new("ctrl-r", RefreshView, Some("Workspace")),
        KeyBinding::new("cmd-q", QuitApp, Some("Workspace")),
        KeyBinding::new("ctrl-q", QuitApp, Some("Workspace")),
        KeyBinding::new("cmd-f", FindInResults, Some("Documents")),
        KeyBinding::new("ctrl-f", FindInResults, Some("Documents")),
        KeyBinding::new("escape", CloseSearch, Some("Documents")),
        KeyBinding::new("escape", CloseSearch, Some("Documents && Input")),
        KeyBinding::new("cmd-f", FindInSidebar, Some("Sidebar")),
        KeyBinding::new("ctrl-f", FindInSidebar, Some("Sidebar")),
        KeyBinding::new("escape", CloseSidebarSearch, Some("Sidebar")),
        KeyBinding::new("cmd-s", SaveDocument, Some("Documents && !Input")),
        KeyBinding::new("ctrl-s", SaveDocument, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-s", DiscardDocumentChanges, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-s", DiscardDocumentChanges, Some("Documents && !Input")),
        KeyBinding::new("cmd-e", EditDocumentJson, Some("Documents && !Input")),
        KeyBinding::new("ctrl-e", EditDocumentJson, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-j", CopyDocumentJson, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-j", CopyDocumentJson, Some("Documents && !Input")),
        KeyBinding::new("cmd-d", DuplicateDocument, Some("Documents && !Input")),
        KeyBinding::new("ctrl-d", DuplicateDocument, Some("Documents && !Input")),
        KeyBinding::new("backspace", DeleteDocument, Some("Documents && !Input")),
        KeyBinding::new("delete", DeleteDocument, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-backspace", DeleteCollection, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-backspace", DeleteCollection, Some("Documents && !Input")),
        KeyBinding::new("backspace", DeleteDatabase, Some("Database && !Input")),
        KeyBinding::new("delete", DeleteDatabase, Some("Database && !Input")),
        KeyBinding::new(
            "backspace",
            DeleteConnection,
            Some("Workspace && !Documents && !Database && !Input"),
        ),
        KeyBinding::new(
            "delete",
            DeleteConnection,
            Some("Workspace && !Documents && !Database && !Input"),
        ),
        KeyBinding::new("cmd-shift-v", PasteDocuments, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-v", PasteDocuments, Some("Documents && !Input")),
        KeyBinding::new("alt-enter", EditValueType, Some("Documents && !Input")),
        KeyBinding::new("alt-return", EditValueType, Some("Documents && !Input")),
        KeyBinding::new("f2", RenameField, Some("Documents && !Input")),
        KeyBinding::new("alt-backspace", RemoveSelectedField, Some("Documents && !Input")),
        KeyBinding::new("alt-delete", RemoveSelectedField, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-a", AddField, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-a", AddField, Some("Documents && !Input")),
        KeyBinding::new("cmd-alt-a", AddElement, Some("Documents && !Input")),
        KeyBinding::new("ctrl-alt-a", AddElement, Some("Documents && !Input")),
        KeyBinding::new("cmd-alt-backspace", RemoveMatchingValues, Some("Documents && !Input")),
        KeyBinding::new("ctrl-alt-backspace", RemoveMatchingValues, Some("Documents && !Input")),
        KeyBinding::new("cmd-c", CopyValue, Some("Documents && !Input")),
        KeyBinding::new("ctrl-c", CopyValue, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-c", CopyKey, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-c", CopyKey, Some("Documents && !Input")),
        KeyBinding::new("cmd-k", OpenActionBar, Some("Workspace")),
        KeyBinding::new("ctrl-k", OpenActionBar, Some("Workspace")),
        KeyBinding::new("cmd-alt-1", ShowDocumentsSubview, Some("Documents")),
        KeyBinding::new("cmd-alt-2", ShowIndexesSubview, Some("Documents")),
        KeyBinding::new("cmd-alt-3", ShowStatsSubview, Some("Documents")),
        KeyBinding::new("cmd-alt-4", ShowAggregationSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-1", ShowDocumentsSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-2", ShowIndexesSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-3", ShowStatsSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-4", ShowAggregationSubview, Some("Documents")),
        KeyBinding::new("cmd-enter", RunAggregation, Some("Documents && Aggregation")),
        KeyBinding::new("ctrl-enter", RunAggregation, Some("Documents && Aggregation")),
        KeyBinding::new("secondary-enter", RunAggregation, Some("Documents && Aggregation")),
        KeyBinding::new("cmd-shift-enter", RunAggregation, Some("Documents && Aggregation")),
        KeyBinding::new("ctrl-shift-enter", RunAggregation, Some("Documents && Aggregation")),
        KeyBinding::new("cmd-shift-f", FormatAggregationStage, Some("Documents && Aggregation")),
        KeyBinding::new("ctrl-shift-f", FormatAggregationStage, Some("Documents && Aggregation")),
        KeyBinding::new(
            "cmd-shift-k",
            ClearAggregationStage,
            Some("Documents && Aggregation && Input"),
        ),
        KeyBinding::new(
            "ctrl-shift-k",
            ClearAggregationStage,
            Some("Documents && Aggregation && Input"),
        ),
        KeyBinding::new(
            "cmd-shift-backspace",
            ClearAggregationStage,
            Some("Documents && Aggregation && Input"),
        ),
        KeyBinding::new(
            "ctrl-shift-backspace",
            ClearAggregationStage,
            Some("Documents && Aggregation && Input"),
        ),
        KeyBinding::new(
            "up",
            SelectPrevAggregationStage,
            Some("Documents && Aggregation && !Input"),
        ),
        KeyBinding::new(
            "down",
            SelectNextAggregationStage,
            Some("Documents && Aggregation && !Input"),
        ),
        KeyBinding::new("cmd-d", DuplicateAggregationStage, Some("Documents && Aggregation")),
        KeyBinding::new("ctrl-d", DuplicateAggregationStage, Some("Documents && Aggregation")),
        KeyBinding::new(
            "cmd-shift-e",
            ToggleAggregationStageEnabled,
            Some("Documents && Aggregation"),
        ),
        KeyBinding::new(
            "ctrl-shift-e",
            ToggleAggregationStageEnabled,
            Some("Documents && Aggregation && !Input"),
        ),
        KeyBinding::new(
            "delete",
            DeleteAggregationStage,
            Some("Documents && Aggregation && !Input"),
        ),
        KeyBinding::new(
            "backspace",
            DeleteAggregationStage,
            Some("Documents && Aggregation && !Input"),
        ),
        KeyBinding::new("cmd-shift-up", MoveAggregationStageUp, Some("Documents && Aggregation")),
        KeyBinding::new(
            "cmd-shift-down",
            MoveAggregationStageDown,
            Some("Documents && Aggregation"),
        ),
        KeyBinding::new("ctrl-shift-up", MoveAggregationStageUp, Some("Documents && Aggregation")),
        KeyBinding::new(
            "ctrl-shift-down",
            MoveAggregationStageDown,
            Some("Documents && Aggregation"),
        ),
    ]
}
