use gpui::{App, KeyBinding, actions};

actions!(
    openmango,
    [
        QuitApp,
        NewConnection,
        CreateDatabase,
        CreateCollection,
        CreateIndex,
        InsertDocument,
        RefreshView,
        CloseTab,
        NextTab,
        PrevTab,
        FindInResults,
        CloseSearch,
        SaveDocument,
        DiscardDocumentChanges,
        EditDocumentJson,
        DuplicateDocument,
        DeleteDocument,
        DeleteCollection,
        DeleteDatabase,
        DeleteConnection,
        PasteDocuments,
        ShowDocumentsSubview,
        ShowIndexesSubview,
        ShowStatsSubview,
    ]
);

pub fn bind_default_keymap(cx: &mut App) {
    cx.bind_keys(default_keybindings());
}

fn default_keybindings() -> Vec<KeyBinding> {
    vec![
        KeyBinding::new("cmd-n", InsertDocument, Some("Documents && !Indexes && !Stats")),
        KeyBinding::new("ctrl-n", InsertDocument, Some("Documents && !Indexes && !Stats")),
        KeyBinding::new("cmd-n", CreateIndex, Some("Documents && Indexes")),
        KeyBinding::new("ctrl-n", CreateIndex, Some("Documents && Indexes")),
        KeyBinding::new("cmd-n", CreateCollection, Some("Database")),
        KeyBinding::new("ctrl-n", CreateCollection, Some("Database")),
        KeyBinding::new("cmd-n", NewConnection, Some("Workspace && Welcome")),
        KeyBinding::new("ctrl-n", NewConnection, Some("Workspace && Welcome")),
        KeyBinding::new("cmd-n", NewConnection, Some("Workspace && Databases")),
        KeyBinding::new("ctrl-n", NewConnection, Some("Workspace && Databases")),
        KeyBinding::new("cmd-n", NewConnection, Some("Workspace && Collections")),
        KeyBinding::new("ctrl-n", NewConnection, Some("Workspace && Collections")),
        KeyBinding::new("cmd-shift-n", CreateDatabase, Some("Workspace && !Documents")),
        KeyBinding::new("ctrl-shift-n", CreateDatabase, Some("Workspace && !Documents")),
        KeyBinding::new("cmd-w", CloseTab, Some("Workspace")),
        KeyBinding::new("ctrl-w", CloseTab, Some("Workspace")),
        KeyBinding::new("ctrl-tab", NextTab, Some("Workspace")),
        KeyBinding::new("ctrl-shift-tab", PrevTab, Some("Workspace")),
        KeyBinding::new("cmd-r", RefreshView, Some("Workspace")),
        KeyBinding::new("ctrl-r", RefreshView, Some("Workspace")),
        KeyBinding::new("cmd-q", QuitApp, Some("Workspace")),
        KeyBinding::new("ctrl-q", QuitApp, Some("Workspace")),
        KeyBinding::new("cmd-f", FindInResults, Some("Documents")),
        KeyBinding::new("ctrl-f", FindInResults, Some("Documents")),
        KeyBinding::new("escape", CloseSearch, Some("Documents")),
        KeyBinding::new("escape", CloseSearch, Some("Documents && Input")),
        KeyBinding::new("cmd-s", SaveDocument, Some("Documents && !Input")),
        KeyBinding::new("ctrl-s", SaveDocument, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-s", DiscardDocumentChanges, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-s", DiscardDocumentChanges, Some("Documents && !Input")),
        KeyBinding::new("cmd-e", EditDocumentJson, Some("Documents && !Input")),
        KeyBinding::new("ctrl-e", EditDocumentJson, Some("Documents && !Input")),
        KeyBinding::new("cmd-d", DuplicateDocument, Some("Documents && !Input")),
        KeyBinding::new("ctrl-d", DuplicateDocument, Some("Documents && !Input")),
        KeyBinding::new("backspace", DeleteDocument, Some("Documents && !Input")),
        KeyBinding::new("delete", DeleteDocument, Some("Documents && !Input")),
        KeyBinding::new("cmd-shift-backspace", DeleteCollection, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-backspace", DeleteCollection, Some("Documents && !Input")),
        KeyBinding::new("backspace", DeleteDatabase, Some("Database && !Input")),
        KeyBinding::new("delete", DeleteDatabase, Some("Database && !Input")),
        KeyBinding::new(
            "backspace",
            DeleteConnection,
            Some("Workspace && !Documents && !Database && !Input"),
        ),
        KeyBinding::new(
            "delete",
            DeleteConnection,
            Some("Workspace && !Documents && !Database && !Input"),
        ),
        KeyBinding::new("cmd-shift-v", PasteDocuments, Some("Documents && !Input")),
        KeyBinding::new("ctrl-shift-v", PasteDocuments, Some("Documents && !Input")),
        KeyBinding::new("cmd-alt-1", ShowDocumentsSubview, Some("Documents")),
        KeyBinding::new("cmd-alt-2", ShowIndexesSubview, Some("Documents")),
        KeyBinding::new("cmd-alt-3", ShowStatsSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-1", ShowDocumentsSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-2", ShowIndexesSubview, Some("Documents")),
        KeyBinding::new("ctrl-alt-3", ShowStatsSubview, Some("Documents")),
    ]
}
